### ISSUE TITLE
Lead update cron

### ISSUE THREAD

**Issue by jacekelgda** [x-team/cavalry-bot#10]
We need to figure out how often we should ask about the status of need.
One smart solution to prevent overflow of notification is to wait with new message about the lead until the previous one is answered.

We also need to figure out if we want to send out all notifications at once or exactly a week from when it was created. That is a preference of biz-dev person.

**Comment by mccrodp** [comment]
>One smart solution to prevent overflow of notification is to wait with new message about the lead until the previous one is answered.

This sounds like a nice idea, but I'm wondering does it cause any issue. What if they wanted to wait until after a call on a particular lead response, but were able to answer the others. They cannot get to them without answering the next in the queue or just postpone answering all. I think this could be good, but also, I think 1 week from original post-date timestamp is more reliable for future.

So, whatever is easiest for the MVP and then the "1 week from original post-date" when we get time.

**Comment by mccrodp** [comment]
You are right though in what you said earlier, it is even better if we ask Bizdev, but I think we can ask once they get a feel for how it is working for them with the "1 week from original post-date" option first, then we update as requested, if it's better.

**Comment by jacekelgda** [comment]
About your previous comment, it would only hold up next messages about the lead that they already got a notification about. So it prevents getting a second notification about the same lead if you didn't answer a week ago anyway.

**Comment by jacekelgda** [comment]
New specs:

cron should notify cerate date + 7days ( weekly )
we should hold notifications per role if the answer was not provided.

**Comment by mccrodp** [comment]
Got it, and like it. 👍

**Comment by mccrodp** [comment]
Is this one done @jacekelgda, it's weekly, right?

**Comment by jacekelgda** [comment]
yes, Monday around noon EU time.
