### ISSUE TITLE
Add TECH value to template

### ISSUE THREAD

**Issue by mccrodp** [x-team/cavalry-bot#55]
Following on from https://github.com/x-team/cavalry-bot/issues/51, can we add `TECH` to the template like so:

```
SHORTLIST: %shortlist,
TIMEZONE: %timezone,
RATE: %rate
TECH: %tech1, %tech2, %tech3
```

In this case, does this format break the existing functionality as this field is CSV inside a CSV? We can always bundle the whole CSV string `%tech1, %tech2, %tech3` into a column if that's possible. We can look to manipulate that later via some search functionality that connects up to that table data.

Cheers.

**Comment by karolsojko** [comment]
@mccrodp it won't break antyhing. `%tech1`, `%tech2`, `%tech3`, `...` will be stored as separate values in an array as the value of `tech` field in the record. So they can be searched and reused later on
